server:
  port: 8002
spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://localhost/msvc-cursos
    username: cursos-admin
    password: 12345
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
